### ISSUE TITLE
Compatibility with tibbles

### ISSUE THREAD

**Issue by MarkPaulin** [DiegoZardetto/ReGenesees#3]
Some functions in this package throw an error if the user supplies data as a tibble rather than a data.frame, and the error message could be confusing to users who don't understand the differences between how tibbles and data.frames behave. Here's an example (based on the help page for `ext.calibrated()`):

``` r
suppressMessages(library(ReGenesees))

data(sbs)

sbsdes <- e.svydesign(data = sbs, ids = ~id, strata = ~strata,
                      weights = ~weight, fpc = ~fpc)

pop <- pop.template(data = sbsdes, calmodel = ~y:nace.macro + emp.cl + emp.num - 1,
                    partition = ~dom3)

pop <- fill.template(universe = sbs.frame, template = pop)
#> 
#> # Coherence check between 'universe' and 'template': OK

sbscal <- e.calibrate(design = sbsdes, df.population = pop, calfun = "logit",
                      bounds = c(0.8, 1.3), sigma2 = ~emp.num)

w <- weights(sbscal)
sbs.ext <- tibble::tibble(sbs, w.ext = w)

sbscal.ext <- ext.calibrated(data = sbs.ext, ids = ~id, strata = ~strata,
                             weights = ~weight, fpc = ~fpc,
                             weights.cal = ~w.ext,
                             calmodel = ~y:nace.macro + emp.cl + emp.num - 1,
                             partition = ~dom3, sigma2 = ~emp.num)
#> Error in ext.calibrated(data = sbs.ext, ids = ~id, strata = ~strata, weights = ~weight, : Weights variable weight is not numeric
```

<sup>Created on 2024-12-09 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

This comes from [this line](https://github.com/DiegoZardetto/ReGenesees/blob/37248e65ed2737de41792d0e567561791a0205a4/R/ext.calibrated.R#L40). Tibbles have `drop = FALSE` as the default when using `[` to extract a single column, so this could be changed by switching `data[, weights.char]` to `data[[weights.char]]`.

Would you be willing to consider a pull request to change this? I'm curious how this package works so contributing small changes like this would be useful for me.

**Comment by DiegoZardetto** [comment]
Hi MarkPaulin,

Thank you for pointing this out.

I mistakenly believed that I had resolved ReGenesees' compatibility issues with tibbles in version 2.3 (as noted [here](https://diegozardetto.github.io/ReGenesees/news/index.html#:~:text=ReGenesees%20predates%20the%20tidyverse%2C%20and%20ReGenesees%20functions%20were%20not%20intended%20to%20accept%20in%20input%20%E2%80%98tibbles%E2%80%99%20where%20data%20frame%20had%20always%20been%20documented%20to%20be%20required.%20To%20avoid%20issues%20with%20%E2%80%98tibbles%E2%80%99%2C%20now%20ReGenesees%20silently%20converts%20%E2%80%98tibbles%E2%80%99%20to%20plain%20data%20frames%20before%20processing%20them.)).

I will address the issue with ext.calibrated() by silently converting the passed 'data' argument to a data.frame, as I have done with other ReGenesees functions.

I’m glad to see your interest in experimenting with ReGenesees!

Please don’t hesitate to reach out if you need clarification, find bugs, or simply wish to share your thoughts.

Best regards,
D.

**Comment by DiegoZardetto** [comment]
Hi Mark,

I've just pushed the fix to Github (as noted [here](https://diegozardetto.github.io/ReGenesees/news/index.html#:~:text=Function%20ext.calibrated()%20had%20a%20residual%20compatibility%20issue%20with%20tibbles%20(thanks%20to%20MarkPaulin%20for%20spotting%20this).%20Fixed.)).

I think it works but feel free to double-check.

Thanks.

Best,
D.

**Comment by DiegoZardetto** [comment]
The issue has been solved and no longer exists in the development version of ReGenesees 2.4.
D.

**Comment by MarkPaulin** [comment]
That's brilliant, thank you for the quick response and fix!
